namespace DataManager.Mapping;

public enum ChatStatus
{
    WAIT_COMMAND,
    WAIT_FILE_SELECTION_OPTION,
    WAIT_FILE_SELECTION_LOADING,
    CHOOSE_SELECTION_FIELDS,
    CHOOSE_SELECTION_PARAMS,
    WAIT_SELECTION_SAVING_TYPE
}
