namespace DataManager.Mapping;

public enum ChatStatus
{
    WAIT_COMMAND,
    WAIT_FILE_SELECTION_OPTION,
    WAIT_FILE_SELECTION_LOADING,
    CHOOSE_SELECTION_FIELDS,
    CHOOSE_SELECTION_PARAMS,
    WAIT_SELECTION_SAVING_TYPE,

    WAIT_FILE_SORTING_OPTION,
    WAIT_FILE_SORTING_LOADING,
    CHOOSE_SORTING_FIELDS,
    CHOOSE_SORTING_PARAMS,
    WAIT_SORTING_SAVING_TYPE,
}
